# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fee6b108f021b18a31f4976280e4269bdeaaad4455030984f14fa3879f3816f2ee560596a834cc1c78379ec2a021954c13daff7e7347cab3495512335c92f697

test:
  secret_key_base: 9fb4a3cd6ba1188c74bbfc6547510c526860b6b7ac6a7b25969320722dd6805ab8689ec6c4cdffcd7066ff6be26c1a7ba105b3c571e3d068a9786917b26badfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
